<?php

namespace Database\Seeders;

use App\Models\Personnel;
use App\Models\Site;
use App\Models\Localite;
use Illuminate\Database\Seeder;

class PersonnelSeeder extends Seeder
{
    public function run(): void
    {
        // S'assurer que le site PE (Peni) existe
        $sitePeni = Site::firstOrCreate(
            ['code_site' => 'PE'],
            ['nom_site' => 'Peni']
        );

        $personnels = [
            [
                'matricule'           => 'PE-2026-0001',
                'nom'                 => 'OUATTARA',
                'prenom'              => 'OUMAR',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '64252049',
                'tel_compte_wave'     => '64252049',
                'localite_code'       => '106', // PENI
                'num_acte_naissance'  => 'N°775 du 06/07/2005',
                'date_naissance'      => '1999-12-31',
                'lieu_naissance'      => 'TIEN',
                'sexe'                => 'M',
                'est_marie'           => false,
                'num_cnib'            => 'B9169238',
                'date_cnib'           => '2017-03-29',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0002',
                'nom'                 => 'OUATTARA',
                'prenom'              => 'KARIM',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '05076049',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°130 du 20/11/2006',
                'date_naissance'      => '2006-09-26',
                'lieu_naissance'      => 'PENI',
                'sexe'                => 'M',
                'est_marie'           => false,
                'num_cnib'            => null,
                'date_cnib'           => null,
                'lieu_cnib'           => null,
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0003',
                'nom'                 => 'BAADHIO',
                'prenom'              => 'SALIFOU',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '75899170',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°1631 du 19/12/2013',
                'date_naissance'      => '2002-12-31',
                'lieu_naissance'      => 'GAYERI',
                'sexe'                => 'M',
                'est_marie'           => false,
                'num_cnib'            => 'B11144791',
                'date_cnib'           => '2019-04-18',
                'lieu_cnib'           => 'GAYERI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0004',
                'nom'                 => 'OUATTARA',
                'prenom'              => 'ABDOULAYE',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '77630047',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°2597 du 20/07/2015',
                'date_naissance'      => '2004-12-31',
                'lieu_naissance'      => 'NOUMOUKIEDOUGOU',
                'sexe'                => 'M',
                'est_marie'           => false,
                'num_cnib'            => 'B22217071',
                'date_cnib'           => '2025-11-13',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0005',
                'nom'                 => 'BARRO',
                'prenom'              => 'FOUSSENI',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '66908700',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°766 du 30/05/2022',
                'date_naissance'      => '2006-01-01',
                'lieu_naissance'      => 'PENI',
                'sexe'                => 'M',
                'est_marie'           => false,
                'num_cnib'            => 'B19156016',
                'date_cnib'           => '2023-11-27',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0006',
                'nom'                 => 'BOLY',
                'prenom'              => 'ALY',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '65811297',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°496 du 26/11/2007',
                'date_naissance'      => '2003-02-28',
                'lieu_naissance'      => 'PENI',
                'sexe'                => 'M',
                'est_marie'           => false,
                'num_cnib'            => 'B17583914',
                'date_cnib'           => '2022-09-17',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0007',
                'nom'                 => 'SIDIBE',
                'prenom'              => 'OROKIATOU',
                'surnom'              => 'S/C DIALLO DAOUDA',
                'niveau_etude'        => null,
                'telephone'           => '66303534',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°5040 du 27/07/2012',
                'date_naissance'      => '2003-12-31',
                'lieu_naissance'      => 'KOUAKOUALE',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B18037538',
                'date_cnib'           => '2023-02-27',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0008',
                'nom'                 => 'DIANDE',
                'prenom'              => 'FADIMA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '74662127',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N° 1330 du 23/03/2017',
                'date_naissance'      => '1999-12-31',
                'lieu_naissance'      => 'NATIABOANI',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B10178020',
                'date_cnib'           => '2018-06-05',
                'lieu_cnib'           => 'FADA N\'GOURMA',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0009',
                'nom'                 => 'YARO',
                'prenom'              => 'RAMATA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '56290709',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°499/2018',
                'date_naissance'      => '2001-01-01',
                'lieu_naissance'      => 'KOUDOUGOU',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => null,
                'date_cnib'           => null,
                'lieu_cnib'           => null,
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0010',
                'nom'                 => 'SANFO',
                'prenom'              => 'LATIFATA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '57981217',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°325 du 05/11/2010',
                'date_naissance'      => '2003-01-01',
                'lieu_naissance'      => 'NIABLE/CIV',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B20072449',
                'date_cnib'           => '2024-07-22',
                'lieu_cnib'           => 'BOBO-DIOULASSO',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0011',
                'nom'                 => 'TRAORE',
                'prenom'              => 'TENE',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '05269056',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°1190 du 04/07/2009',
                'date_naissance'      => '2004-01-11',
                'lieu_naissance'      => 'PENI',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B19202532',
                'date_cnib'           => '2023-11-29',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0012',
                'nom'                 => 'CISSE',
                'prenom'              => 'INSITA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '05118966',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°043 du 06/03/2000',
                'date_naissance'      => '2000-02-19',
                'lieu_naissance'      => 'SANI',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B19099936',
                'date_cnib'           => '2023-11-10',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0013',
                'nom'                 => 'SAWADOGO',
                'prenom'              => 'FATIMATA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '74301422',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°3199 du 17/12/2019',
                'date_naissance'      => '2000-01-01',
                'lieu_naissance'      => 'PENI',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B12930682',
                'date_cnib'           => '2020-01-22',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0014',
                'nom'                 => 'OUATTARA',
                'prenom'              => 'KOUROUBI',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '57668572',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°3817 du 18/09/2009',
                'date_naissance'      => '2006-08-06',
                'lieu_naissance'      => 'NOUMOUDARA',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B18427766',
                'date_cnib'           => '2023-05-12',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0015',
                'nom'                 => 'SIDIBE',
                'prenom'              => 'DJENEBA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '77132275',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => null,
                'date_naissance'      => '1984-01-01',
                'lieu_naissance'      => 'KOUKA',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B22976725',
                'date_cnib'           => '2025-09-30',
                'lieu_cnib'           => 'BOBO-DIOULASSO',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0016',
                'nom'                 => 'SOMA',
                'prenom'              => 'MINATA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '07873525',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°1216 du 20/10/2020',
                'date_naissance'      => '2006-01-01',
                'lieu_naissance'      => 'GOUINDOUGOUBA',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B17583935',
                'date_cnib'           => '2022-09-17',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0017',
                'nom'                 => 'OUATTARA',
                'prenom'              => 'KADI',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '56728776',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°4982 du 25/11/2009',
                'date_naissance'      => '2006-11-02',
                'lieu_naissance'      => 'NOUMOUDARA',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => null,
                'date_cnib'           => null,
                'lieu_cnib'           => null,
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0018',
                'nom'                 => 'MILLOGO',
                'prenom'              => 'AMINATA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '55447668',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°1452/2006',
                'date_naissance'      => '1997-10-30',
                'lieu_naissance'      => 'BOBO-DIOULASSO',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B15013026',
                'date_cnib'           => '2020-07-10',
                'lieu_cnib'           => 'BOBO-DIOULASSO',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0019',
                'nom'                 => 'SANOU',
                'prenom'              => 'SOU EDITH',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '05502084',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => null,
                'date_naissance'      => '2003-09-16',
                'lieu_naissance'      => 'KOUMI',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B14011063',
                'date_cnib'           => '2021-11-30',
                'lieu_cnib'           => 'BOBO-DIOULASSO',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0020',
                'nom'                 => 'NEYA',
                'prenom'              => 'RISSANATA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '77991584',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°958/2006',
                'date_naissance'      => '1993-03-12',
                'lieu_naissance'      => 'BOBO-DIOULASSO',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B13229718',
                'date_cnib'           => '2020-04-15',
                'lieu_cnib'           => 'BOBO-DIOULASSO',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0021',
                'nom'                 => 'DIALLO',
                'prenom'              => 'HAOUA',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '66007105',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°865 du 16/06/2014',
                'date_naissance'      => '1996-01-01',
                'lieu_naissance'      => 'DRAMANDOUGOU',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B14413951',
                'date_cnib'           => '2021-06-11',
                'lieu_cnib'           => 'TIEFORA',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
            [
                'matricule'           => 'PE-2026-0022',
                'nom'                 => 'BANDE',
                'prenom'              => 'BINTOU',
                'surnom'              => null,
                'niveau_etude'        => null,
                'telephone'           => '65792094',
                'tel_compte_wave'     => null,
                'localite_code'       => '106',
                'num_acte_naissance'  => 'N°1246 du 20/02/2017',
                'date_naissance'      => '1981-12-31',
                'lieu_naissance'      => 'NAMAGDOU',
                'sexe'                => 'F',
                'est_marie'           => false,
                'num_cnib'            => 'B10823909',
                'date_cnib'           => '2019-03-15',
                'lieu_cnib'           => 'PENI',
                'num_cnss'            => null,
                'date_cnss'           => null,
                'classification'      => 'TEMPORAIRE',
            ],
        ];

        foreach ($personnels as $data) {
            $localite = Localite::where('code_localite', $data['localite_code'])->first();

            if (!$localite) {
                $localite = Localite::firstOrCreate(
                    ['code_localite' => $data['localite_code']],
                    ['nom_localite' => $data['lieu_naissance'] ?? 'Inconnu']
                );
            }

            Personnel::updateOrCreate(
                ['matricule' => $data['matricule']],
                [
                    'nom'                   => $data['nom'],
                    'prenom'                => $data['prenom'],
                    'surnom'                => $data['surnom'],
                    'niveau_etude'          => $data['niveau_etude'],
                    'telephone'             => $data['telephone'],
                    'tel_compte_wave'       => $data['tel_compte_wave'],
                    'localite_domicile_id'  => $localite->id,
                    'num_acte_naissance'    => $data['num_acte_naissance'],
                    'date_naissance'        => $data['date_naissance'],
                    'lieu_naissance'        => $data['lieu_naissance'],
                    'sexe'                  => $data['sexe'],
                    'est_marie'             => $data['est_marie'],
                    'num_cnib'              => $data['num_cnib'],
                    'date_cnib'             => $data['date_cnib'],
                    'lieu_cnib'             => $data['lieu_cnib'],
                    'num_cnss'              => $data['num_cnss'],
                    'date_cnss'             => $data['date_cnss'],
                    'site_travail_id'       => $sitePeni->id,
                    'section_defaut_id'     => null,
                    'actif'                 => true,
                    'preference_paiement'   => 'ESPECES',
                    'classification'        => $data['classification'],
                ]
            );
        }
    }
}